import React from "react";
import {
  Modal,
    View,
      Text,
        TouchableOpacity,
          StyleSheet,
          } from "react-native";

          import Colors from "../constants/colors";

          interface CustomModalProps {
            visible: boolean;
              title: string;
                message: string;
                  confirmText: string;
                    cancelText: string;
                      onConfirm: () => void;
                        onCancel: () => void;
                        }

                        export default function CustomModal({
                          visible,
                            title,
                              message,
                                confirmText,
                                  cancelText,
                                    onConfirm,
                                      onCancel,
                                      }: CustomModalProps) {
                                        return (
                                            <Modal
                                                  transparent
                                                        animationType="fade"
                                                              visible={visible}
                                                                  >
                                                                        <View style={styles.overlay}>
                                                                                <View style={styles.modal}>
                                                                                          <Text style={styles.title}>
                                                                                                      {title}
                                                                                                                </Text>

                                                                                                                          <Text style={styles.message}>
                                                                                                                                      {message}
                                                                                                                                                </Text>

                                                                                                                                                          <View style={styles.buttons}>
                                                                                                                                                                      <TouchableOpacity
                                                                                                                                                                                    style={styles.cancel}
                                                                                                                                                                                                  onPress={onCancel}
                                                                                                                                                                                                              >
                                                                                                                                                                                                                            <Text style={styles.cancelText}>
                                                                                                                                                                                                                                            {cancelText}
                                                                                                                                                                                                                                                          </Text>
                                                                                                                                                                                                                                                                      </TouchableOpacity>

                                                                                                                                                                                                                                                                                  <TouchableOpacity
                                                                                                                                                                                                                                                                                                style={styles.confirm}
                                                                                                                                                                                                                                                                                                              onPress={onConfirm}
                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                        <Text style={styles.confirmText}>
                                                                                                                                                                                                                                                                                                                                                        {confirmText}
                                                                                                                                                                                                                                                                                                                                                                      </Text>
                                                                                                                                                                                                                                                                                                                                                                                  </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                            </View>
                                                                                                                                                                                                                                                                                                                                                                                                    </View>
                                                                                                                                                                                                                                                                                                                                                                                                          </View>
                                                                                                                                                                                                                                                                                                                                                                                                              </Modal>
                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                                  overlay: {
                                                                                                                                                                                                                                                                                                                                                                                                                      flex: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                          backgroundColor: "rgba(0,0,0,0.65)",
                                                                                                                                                                                                                                                                                                                                                                                                                              justifyContent: "center",
                                                                                                                                                                                                                                                                                                                                                                                                                                  alignItems: "center",
                                                                                                                                                                                                                                                                                                                                                                                                                                    },

                                                                                                                                                                                                                                                                                                                                                                                                                                      modal: {
                                                                                                                                                                                                                                                                                                                                                                                                                                          width: "85%",
                                                                                                                                                                                                                                                                                                                                                                                                                                              backgroundColor: "#111827",
                                                                                                                                                                                                                                                                                                                                                                                                                                                  borderRadius: 18,
                                                                                                                                                                                                                                                                                                                                                                                                                                                      padding: 22,
                                                                                                                                                                                                                                                                                                                                                                                                                                                        },

                                                                                                                                                                                                                                                                                                                                                                                                                                                          title: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                              color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontSize: 22,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontWeight: "700",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          marginBottom: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              message: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  color: "#cbd5e1",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontSize: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          marginBottom: 22,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              buttons: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  flexDirection: "row",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      justifyContent: "flex-end",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          cancel: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              marginRight: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  cancelText: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      color: "#94a3b8",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fontSize: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              confirm: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  backgroundColor: "#ef4444",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      paddingHorizontal: 18,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          paddingVertical: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              borderRadius: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  confirmText: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fontWeight: "700",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });